### ISSUE TITLE
Migrate to different org?

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/maven-model-helper#147]
Every repo (~20) in the fabric8-launcher org is about to be archived, so perhaps it would be best to archive the entire org, except that the "maven-model-helper" is still actively being developed! So perhaps this repo can be migrated to some other org?

Wdyt @gastaldi ?

**Comment by gastaldi** [comment]
Hm, https://github.com/fabric8io would be the natural place, but I don't have any administrative permission under the org, I'll investigate what I can do, thanks for the heads-up @quintesse !

**Comment by gastaldi** [comment]
Moved to https://github.com/fabric8io/maven-model-helper. Thanks!

**Comment by quintesse** [comment]
Yay! Thanks George :-)
